import React from 'react';

function TermsAndConditions() {
  return (
    <div className=" min-h-screen p-4 w-full">
      <div className="max-w-3xl mx-auto bg-white p-6 rounded shadow">
        <h1 className="text-3xl font-semibold text-center mb-6">Terms and Conditions</h1>

        {/* Section 1: Acceptance of Terms */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
          <p>
            Welcome to Chat Paperz! By using our services, you agree to comply with and be bound by these terms and conditions. If you do not agree to these terms, please refrain from using our app.
          </p>
        </section>

        {/* Section 2: User Registration */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. User Registration</h2>
          <p>
            In order to access certain features of our app, you may be required to register an account. You are responsible for maintaining the confidentiality of your account information and passwords. You agree to provide accurate and current information during the registration process.
          </p>
        </section>

        {/* Section 3: Privacy Policy */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">3. Privacy Policy</h2>
          <p>
            Your use of our app is also governed by our Privacy Policy, which outlines how we collect, use, and protect your personal information. By using our app, you consent to our Privacy Policy.
          </p>
        </section>

        {/* Section 4: Intellectual Property */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">4. Intellectual Property</h2>
          <p>
            You have a license to use the output generated by the app for personal, and commercial purposes.
          </p>
        </section>

        {/* Section 5: User Conduct */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. User Conduct</h2>
          <p>
            While using our app, you agree not to:
            <ul className="list-disc ml-6">
              <li>Engage in any unlawful or harmful activities.</li>
              <li>Attempt to disrupt or interfere with the app&apos;s functionality.</li>
              <li>Upload or share content that violates the rights of others.</li>
            </ul>
          </p>
        </section>

        {/* Section 6: Termination */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">6. Termination</h2>
          <p>
            Chat Paperz reserves the right to terminate or suspend your account at any time for violations of these terms or for any other reason at our discretion. You may also terminate your account by contacting us.
          </p>
        </section>

        {/* Section 7: Changes to Terms */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Changes to Terms</h2>
          <p>
            Chat Paperz may update these terms from time to time. We will notify you of significant changes via email or app notifications. Continued use of the app after such modifications constitutes your acceptance of the updated terms.
          </p>
        </section>

        {/* Section 8: Contact Information */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">8. Contact Information</h2>
          <p>
            If you have any questions or concerns about these terms and conditions, please contact us at using our official email.
          </p>
        </section>
        
      </div>
    </div>
  );
}

export default TermsAndConditions;
